"""Deterministic Markdown report generation.

Every number printed here is produced by the engine at run time; nothing is
transcribed by hand.  Re-running the CLI regenerates all ten documents
byte-for-byte.
"""
from __future__ import annotations

import collections
import os
from typing import Dict, List

from .cipher import is_prime, resolve
from .corpus import ARABIC_DIGITS, Jazariyyah, OPCODE_AR, OPCODE_EN, arabic_number
from .expand import depth_series, evaluate, expand_letter, parse, trace
from .graphtree import TreeGraph
from .hashaddr import BOOTLOADER, HashAddress, OPS_ORDER
from .letters import (ALPHABET_SIZE, ALPHABET_SUM, BY_ORDER, GROUP, NAME,
                      ORDER, VALUE, abjad, breakdown, digital_root,
                      letter_for_value, modulo_letter, normalise,
                      to_abjad_numeral)
from .makharij import MAKHRAJ, SIFAT, makhraj, makhraj_line, sifat_of, triliteral
from .states import OPEN_TA_RASM, STRIDE, analyse_word, open_ta_pairs, state_words
from .synth import _word_index, synthesise

BANNER = ("> Generated by the ABJADCOMPUTER engine. Every value below is a sum of\n"
          "> table look-ups and can be re-checked with pencil and paper.\n")


def _rtl(s: str) -> str:
    return s


def _table(head: List[str], rows: List[List[str]]) -> str:
    out = ["| " + " | ".join(head) + " |",
           "|" + "|".join("---" for _ in head) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def _working(word: str) -> str:
    b = breakdown(word)
    return " + ".join(f"{c}={v}" for c, v in b) + f" = **{sum(v for _, v in b)}**"


# ---------------------------------------------------------------- doc 01
def doc_01(J: Jazariyyah) -> str:
    L = ["# ٠١ — المقدمة الجزرية: التلاوة المتداخلة بالأبيات الأبجدية",
         "# 01 — Al-Muqaddimah al-Jazariyyah, 109 lines interleaved with generated Abjad bridges",
         "", BANNER, ""]
    m = J.meta
    L += [f"**{m['work']}** — {m['author']} (ت {m['author_died_ah']} هـ), نُظمت سنة "
          f"{m['composed_ah']} هـ، بحر {m['metre']}.", "",
          f"- Transmitted lines: **{m['line_count']}**",
          f"- Authorial self-count (line {m['authorial_count_line']}): **{m['authorial_count']}**",
          f"- Lines held to be interpolated: **{', '.join(str(x) for x in m['interpolated_lines'])}**",
          "", "## How to read this document", "",
          "Each numbered entry gives the transmitted line, then a **بيت أبجديّ** — a bridging",
          "couplet synthesised from that line's own arithmetic — then the structural state used",
          "for routing. The bridge is a pure function of the line's numbers, so you can",
          "recompute it from the arithmetic column alone. The bridges are engine output, not",
          "transmitted text, and are marked as such throughout.", "",
          "Bridge template (fixed for all 109 lines, rhyme ـَرْ):", "",
          "```", "جُمْلَتُهُ {total} وَجَذْرُهُ {digital-root} ظَهَرْ",
          "وَبَابُهُ {ring-letter-name} {opcode} لِمَنِ اعْتَبَرْ", "```", "",
          "---", ""]
    cur = None
    for a in J.lines:
        if a.section != cur:
            cur = a.section
            L += [f"## باب {cur}", ""]
        tag = ""
        if a.n in J.meta["interpolated_lines"]:
            tag = "  ⟨**مُقحَم / interpolated**⟩"
        if a.n == J.meta["authorial_count_line"]:
            tag = "  ⟨**بيت العدّ / colophon**⟩"
        L += [f"### {a.n}.{tag}", "",
              "> " + a.sadr + "  ✽  " + a.ajuz, "",
              "*بيت أبجديّ (generated):*", "",
              "> " + a.bridge_sadr + "  ✽  " + a.bridge_ajuz, ""]
        state = (f"ta-bits **{a.ta_bits}**"
                 + (f" ({', '.join(a.ta_words)}; waṣl total {a.total_wasl}, Δ {a.ta_delta})"
                    if a.ta_bits else " (no feminine ending — state fixed)"))
        L += [_table(["صدر", "عجز", "جملة", "abjad numeral", "digital root",
                      "ring (mod 28)", "hash address", "opcode"],
                     [[a.sadr_value, a.ajuz_value, a.total, a.numeral, a.dr,
                       f"{a.ring} = {a.ring_letter}", f"`{a.key}`",
                       f"{a.opcode} — {OPCODE_EN[a.opcode]}"]]),
              "", f"Routing state: {state}.", ""]
    t = J.totals()
    L += ["---", "", "## Column totals", "",
          _table(["quantity", "value"],
                 [["sum of all 109 line-totals", t["sum"]],
                  ["digital root of that sum", digital_root(t["sum"])],
                  ["smallest line", f"line {t['argmin']} = {t['min']}"],
                  ["largest line", f"line {t['argmax']} = {t['max']}"],
                  ["max − min", t["max"] - t["min"]],
                  ["sum of lines 1–107", sum(a.total for a in J.lines[:107])],
                  ["sum of lines 108–109", sum(a.total for a in J.lines[107:])]]),
          ""]
    return "\n".join(L)


# ---------------------------------------------------------------- doc 02
def doc_02(J: Jazariyyah) -> str:
    r = resolve(J)
    tr = r["transformation"]
    qz = r["qaf_zay"]
    wi = _word_index(J)
    at107 = [w for w in wi if w["value"] == 107]
    at109 = [w for w in wi if w["value"] == 109]
    L = ["# ٠٢ — حلّ شفرة «قافٌ وزايٌ»: من ١٠٧ إلى ١٠٩",
         "# 02 — The qāf-wa-zāy cipher: resolving 107 against 109", "", BANNER, "",
         "## 1. The statement", "",
         "The poem counts itself in its own colophon:", "",
         f"> {r['colophon_text']}", "",
         f"In this recension that hemistich stands at ordinal **{r['colophon_ordinal']}** "
         f"of {J.meta['line_count']} transmitted lines.", "",
         "## 2. Reading قافٌ وزايٌ", "",
         "The two words name *letters*, and letters carry weights:", "",
         _table(["letter", "name", "weight"],
                [[c, NAME[c], v] for c, v in qz["letters"]]
                + [["**sum**", "—", f"**{qz['total']}**"]]), "",
         "```", "ق = 100", "ز =   7", "-------", "    107", "```", "",
         "A competing reading takes the two words as words rather than as letter-names:", "",
         _table(["word", "working", "value"],
                [["قاف", _working("قاف"), abjad("قاف")],
                 ["زاي", _working("زاي"), abjad("زاي")],
                 ["**sum**", "—", f"**{qz['word_reading']['total']}**"]]), "",
         f"That gives {qz['word_reading']['total']}, which matches no line count of any "
         "recension. The letter-denoting reading (107) is the one the text supports.", "",
         "## 3. Writing 109 as a scribe would", "",
         "```", "ق = 100", "ط =   9", "-------", "    109", "```", "",
         f"So **107 = قز** and **109 = قط**. Both numerals share the head ق; the whole "
         "dispute is confined to the second letter, ز (7) against ط (9).", "",
         _table(["quantity", "107", "109"],
                [["abjad numeral", tr["numeral_from"], tr["numeral_to"]],
                 ["head letter", tr["shared_head"], tr["shared_head"]],
                 ["tail letter", f"{tr['tail_from'][0]} = {tr['tail_from'][1]}",
                  f"{tr['tail_to'][0]} = {tr['tail_to'][1]}"],
                 ["digital root", f"{tr['dr_from']} = {tr['dr_from_letter']}",
                  f"{tr['dr_to']} = {tr['dr_to_letter']}"],
                 ["prime?", "yes" if is_prime(107) else "no",
                  "yes" if is_prime(109) else "no"]]), "",
         f"- Δ = {tr['delta']} = **{tr['delta_letter']}** ({tr['delta_name']}) — the two surplus lines.",
         "- 107 and 109 are **twin primes** — two primes differing by exactly 2."
         if tr["twin_primes"] else "- 107 and 109 are not both prime.",
         f"- Digital roots run {tr['dr_from']} → {tr['dr_to']}, i.e. "
         f"**{tr['dr_from_letter']}** → **{tr['dr_to_letter']}**: the last letter of the "
         "primordial octet آبجد هوز ح back to its first. The disputed increment carries the "
         "count off the end of the bootloader and around to its origin (see doc 03).", "",
         "## 4. The finding that settles the arithmetic", ""]
    L += ["The colophon does not only state a number. It contains one.", "",
          f"> {r['colophon_text']}", "",
          "The last word of the first hemistich is **الْعَدَدْ** — *the count*. Weigh it:", "",
          "```", "ا =   1", "ل =  30", "ع =  70", "د =   4", "د =   4", "-------", "    109", "```", "",
          f"**الْعَدَدْ = {abjad('العدد')}.** The hemistich that declares the count to be 107 "
          "carries, as its own last word, the number 109 — the count actually transmitted.", "",
          f"Across all {len(wi)} distinct words of the poem, exactly **{len(at109)}** sit at "
          f"address 109:", "",
          _table(["word", "value", "occurs in line(s)"],
                 [[w["word"], w["value"], ", ".join(str(x) for x in w["lines"])]
                  for w in at109]), "",
          "The other is **قَطٍ** — the abjad spelling of 109 — standing inside the mnemonic "
          "for the plosive letters in line 21 (`شَدِيدُهَا لَفْظُ أَجِدْ قَطٍ بَكَتْ`). The two "
          "words in the whole poem that weigh 109 are the numeral for 109 and the word "
          "*count*.", "",
          f"Address 107 is likewise populated — by **{len(at107)}** words:", "",
          _table(["word", "value", "occurs in line(s)"],
                 [[w["word"], w["value"], ", ".join(str(x) for x in w["lines"])]
                  for w in at107]), "",
          "**What this does and does not establish.** The arithmetic is exact and anyone can "
          "recheck it. Whether Ibn al-Jazari intended it is not something the arithmetic can "
          "decide, and this document does not claim it. What is established is that both "
          "numbers of the dispute are present in the colophon: 107 by statement, 109 by "
          "weight.", "",
          "## 5. Why the paradox is visible in print at all", "",
          "The two witnesses collated for this repository order the closing lines "
          "differently, and that difference is the whole mechanism:", ""]
    ap = r["apparatus"]
    L += [_table(["ordinal", "witness A (takw.in, primary)", "witness B (Wikisource)"],
                 [[107, ap["takwin_order"][0], ap["wikisource_order"][0]],
                  [108, ap["takwin_order"][1], ap["wikisource_order"][1]],
                  [109, ap["takwin_order"][2], ap["wikisource_order"][2]]]), "",
          "In **A** the colophon closes the poem at ordinal 107 and the two doxology lines "
          "follow it as an appendix; the statement is true of its own position and nothing "
          "looks wrong. In **B** the same two lines are inserted *before* the colophon, "
          "displacing it to ordinal 109 — and a line reading *“its verses are 107”* sitting "
          "at position 109 is exactly the contradiction readers report.", "",
          "The paradox is therefore not arithmetical but **positional**: it is produced by "
          "where the appendix was spliced, not by any error in the count.", "",
          "## 6. The two surplus lines as hash keys", "",
          "Treated as operational keys rather than as text, the interpolated lines resolve "
          "to addresses that route back into the corpus:", "",
          _table(["line", "text", "total", "numeral", "dr", "ring", "address", "opcode",
                  "total mod 109"],
                 [[k["n"], k["text"], k["total"], k["numeral"], k["dr"],
                   f"{k['ring']} = {k['ring_letter']}", f"`{k['key']}`", k["opcode"],
                   k["unlocks"]] for k in r["interpolation_keys"]]), "",
          f"- Combined weight of the interpolation: **{r['surplus_total']}**, digital root "
          f"**{r['surplus_dr']}**.",
          f"- Line 109 reduces to **{r['interpolation_keys'][1]['unlocks']}** modulo 109 — the "
          f"size of the alphabet itself ({ALPHABET_SIZE}), i.e. the key closes the ring.",
          f"- Both surplus lines share digital root "
          f"{r['interpolation_keys'][0]['dr']}, so they occupy one container and are a single "
          "two-line insertion by the graph's own reckoning.", ""]
    return "\n".join(L)


# ---------------------------------------------------------------- doc 03
def doc_03(J: Jazariyyah) -> str:
    L = ["# ٠٣ — مُقلِع الأبجدية الأولى: آب جد هو زح",
         "# 03 — The primordial alphabet bootloader", "", BANNER, "",
         "The received order of the alphabet is not alphabetical but *numerical*: its first "
         "eight letters carry the units 1–8 in sequence, and they are memorised in pairs. "
         "Those pairs are the engine's four inherited operations.", "",
         "## 1. The base sequence", "",
         _table(["letter", "name", "value", "group"],
                [[c, NAME[c], VALUE[c], GROUP[c]] for c in BY_ORDER[:8]]), "",
         "## 2. Phrasal segmentation", "",
         _table(["pair", "letters", "sum", "abjad numeral", "opcode", "meaning"],
                [[w, " + ".join(f"{c}({VALUE[c]})" for c in ls), s,
                  to_abjad_numeral(s), op, gloss]
                 for w, ls, s, op, gloss in BOOTLOADER]), "",
         "```", "آب : 1 + 2 =  3  -> ج", "جد : 3 + 4 =  7  -> ز",
         "هو : 5 + 6 = 11  -> يا", "زح : 7 + 8 = 15  -> يه", "```", "",
         "## 3. Two facts that make this a machine rather than a mnemonic", "",
         "**(a) The sums are an arithmetic progression of stride 4.**", "",
         "```", "3, 7, 11, 15    differences: 4, 4, 4", "```", "",
         "Consecutive disjoint pairs of consecutive integers always advance by 4, so the four "
         "operations are separated by a constant. That is why an address reduced **modulo 4** "
         "selects exactly one of them, and why the operation table has four entries and not "
         "some other number:", "",
         _table(["address mod 4", "opcode", "effect"],
                [[i, OPS_ORDER[i], OPCODE_EN[OPS_ORDER[i]]] for i in range(4)]), "",
         "**(b) The first two sums stay inside the octet; the last two do not.**", "",
         _table(["pair", "sum", "representable as one letter?", "rendering"],
                [[w, s, "yes" if s <= 9 else "no — carries",
                  to_abjad_numeral(s) + (f"  ({s})" if s > 9 else "")]
                 for w, ls, s, op, gloss in BOOTLOADER]), "",
         "آب→ج and جد→ز land back on letters that are themselves *inside* the source octet "
         f"(positions {ORDER['ج']} and {ORDER['ز']}). هو→11 and زح→15 exceed 9 and must be "
         "written with two cells, يا and يه. The alphabet's own opening therefore demonstrates "
         "a register file of eight single-cell slots plus a carry discipline: values that "
         "overflow the unit range spill into a two-cell composite whose high cell is ي (10).", "",
         "## 4. The memory allocation table", "",
         "Allocating one slot per pair and letting the carry rule decide its width:", ""]
    rows = []
    for w, ls, s, op, gloss in BOOTLOADER:
        num = to_abjad_numeral(s)
        rows.append([w, s, num, len(num), "unit register" if len(num) == 1
                     else "carry pair (high ي = 10)", op,
                     f"`{HashAddress(s, 0, '0').key}`"])
    L += [_table(["pair", "value", "numeral", "cells", "allocation", "opcode", "hash address"],
                 rows), "",
          f"Total allocated: **{sum(s for _, _, s, _, _ in BOOTLOADER)}** = "
          f"{to_abjad_numeral(sum(s for _, _, s, _, _ in BOOTLOADER))} — which is also "
          f"1+2+…+8, the sum of the whole octet. The allocation is exact: nothing in the "
          "first eight letters is left unassigned and nothing is double-counted.", "",
          "## 5. Inheritance and state transition", "",
          "The four opcodes are precisely a tree-walk instruction set:", "",
          "```",
          "آب  PARENT       node -> node.parent            (one level up)",
          "جد  GRANDPARENT  node -> node.parent.parent     (two levels up)",
          "هو  IDENTITY     node -> node                   (hold)",
          "زح  SHIFT        node -> next member of its container  (lateral jump)",
          "```", "",
          "Three of them move on **tree** edges (up, up-twice, stay); the fourth moves on a "
          "**graph** edge (sideways, through the constellation container). The primordial "
          "order thus supplies both link systems of the hybrid structure — vertical "
          "inheritance from آب/جد/هو, horizontal addressing from زح.", "",
          "## 6. Distribution over the corpus", "",
          "Reducing every line of the Jazariyyah modulo 4 gives the opcode each line executes:", ""]
    h = collections.Counter(a.opcode for a in J.lines)
    L += [_table(["opcode", "lines", "share"],
                 [[op, h[op], f"{100*h[op]//len(J.lines)}%"] for op in OPS_ORDER]), "",
          "All four operations are exercised; no line of the poem is unreachable.", ""]
    return "\n".join(L)


# ---------------------------------------------------------------- doc 04
def doc_04(J: Jazariyyah) -> str:
    L = ["# ٠٤ — أطلس البسط المتداخل للحروف",
         "# 04 — Atlas of nested letter expansion", "", BANNER, "",
         "A letter is a name as well as a sign. Replacing each letter by the letters that "
         "spell its name, recursively, turns a single value into a tree whose totals grow "
         "with depth. Level 0 is the bare sign; level 1 is its name; level 2 expands each "
         "letter of that name in turn.", "",
         "## 1. The worked case: ا", "",
         "```", "L0  ا                         = 1",
         "L1  ا -> ا ل ف                 = 1 + 30 + 80          = 111",
         "L2  (ا)(ل)(ف)                  = 111 + 71 + 82        = 264",
         "        ا -> الف = 1+30+80  = 111",
         "        ل -> لام = 30+1+40 =  71",
         "        ف -> فاء = 80+1+1  =  82", "```", ""]
    e2 = expand_letter("ا", 2)
    L += [f"As a first-class expression: `{e2.sexpr()}` = **{e2.value}**", "",
          "The spec's own notation writes the last branch with the defective spelling فا "
          "rather than فاء. The evaluator honours whichever spelling is written:", "",
          "```"] + trace("آ(آ(آلف)ل(لام)ف(فا))") + ["```", "",
          f"`آ(آ(آلف)ل(لام)ف(فا))` = **{evaluate('آ(آ(آلف)ل(لام)ف(فا))')}** (defective فا = 81)",
          f"`{e2.sexpr()}` = **{e2.value}** (plene فاء = 82)", "",
          "Both are reported because both are attested spellings; the engine never guesses "
          "which one a source intends.", "",
          "## 2. Depth series for every letter", "",
          "Totals at L0–L3 under the plene spelling profile:", ""]
    rows = []
    for c in BY_ORDER:
        s = depth_series(c, 3)
        rows.append([c, NAME[c], s[0], s[1], s[2], s[3],
                     f"×{s[1]//s[0] if s[0] else 0}"])
    L += [_table(["letter", "name", "L0", "L1", "L2", "L3", "L1/L0"], rows), "",
          "## 3. Growth", "",
          "Expansion is monotone but not uniform: a letter whose name is spelled with heavy "
          "letters climbs faster than its own weight suggests.", ""]
    ser = [(c, depth_series(c, 2)) for c in BY_ORDER]
    fastest = sorted(ser, key=lambda kv: -(kv[1][1] / kv[1][0]))[:5]
    slowest = sorted(ser, key=lambda kv: (kv[1][1] / kv[1][0]))[:5]
    L += [_table(["fastest L0→L1", "ratio", "", "slowest L0→L1", "ratio"],
                 [[f"{a[0]} ({a[1][0]}→{a[1][1]})", f"{a[1][1]/a[1][0]:.1f}", "",
                   f"{b[0]} ({b[1][0]}→{b[1][1]})", f"{b[1][1]/b[1][0]:.2f}"]
                  for a, b in zip(fastest, slowest)]), "",
          f"ا is the extreme case: weight 1 at L0, {depth_series('ا',1)[1]} at L1 — a factor "
          f"of {depth_series('ا',1)[1]}. The lightest sign carries the heaviest name, because "
          "its name ends in ف (80). This is why ا behaves as the engine's origin: it is the "
          "only node whose expansion changes its order of magnitude twice over.", "",
          "## 4. Expansion of the corpus's own key words", ""]
    rows = []
    for w in ["الحروف", "التجويد", "المقدمة", "العدد", "قط", "مخارج"]:
        v0 = abjad(w)
        from .expand import word_value_at_depth
        rows.append([w, v0, word_value_at_depth(w, 1), word_value_at_depth(w, 2),
                     to_abjad_numeral(v0)])
    L += [_table(["word", "L0", "L1", "L2", "numeral"], rows), "",
          "## 5. Reading an expansion as a tree", ""]
    e = expand_letter("ق", 2)
    L += ["The expansion of ق to depth 2, with positional offsets:", "", "```"] \
        + [f"{'  ' * n.path.count('.')}{n.ch}@{n.path}  = {n.value}" for n in e.walk()] \
        + ["```", "",
           f"Root value {e.value}; {len(e.leaves())} leaves; surface `{e.surface()}`.",
           "Each `@path` is the positional offset component of that node's hash address, so "
           "any sub-tree in this diagram is directly addressable (doc 05).", ""]
    return "\n".join(L)


# ---------------------------------------------------------------- doc 05
def doc_05(J: Jazariyyah) -> str:
    g = J.graph()
    L = ["# ٠٥ — جداول العنونة بالتجزئة",
         "# 05 — Hash address lookup tables", "", BANNER, "",
         "## 1. Address format", "",
         "```", "J<value> / D<depth> / P<path> / S<state>", "",
         "  J  concatenated abjad total of the node's surface form",
         "  D  expansion depth at which the node sits",
         "  P  positional offset inside the parent  (e.g. 29.ajuz.3)",
         "  S  orthographic state bit  0 = waqf (ة→ه=5), 1 = waṣl (ة→ت=400)",
         "```", "",
         "Every component is recomputable from the node itself, so the key is a *function of "
         "the datum* rather than a label assigned to it. That is what makes retrieval a "
         "single dictionary probe instead of a search.", "",
         "## 2. Cost", "", ]
    st = g.stats()
    L += [_table(["operation", "method", "cost"],
                 [["resolve address → node", "dict probe on the key", "O(1) average"],
                  ["fetch a node's container", "dict probe on the bucket handle", "O(1) average"],
                  ["jump to an equivalent node", "index into the container list", "O(1)"],
                  ["enumerate a whole container of k nodes", "list read", "O(k)"],
                  ["execute an address as a function", "op-table dispatch + one hop", "O(1)"]]), "",
         "**On the fully-connected claim.** A container of *k* nodes behaves as a clique — any "
         "member reaches any other in one hop — but the edges are never materialised. Only "
         "membership is stored, so the structure costs O(n) rather than O(n²) while preserving "
         "single-hop reachability. Over this corpus:", "",
         _table(["quantity", "value"],
                [["nodes", st["nodes"]],
                 ["containers", st["containers"]],
                 ["containers with ≥2 members", st["populated_containers"]],
                 ["largest container", st["largest_container"]],
                 ["edges implied (clique semantics)", st["implied_graph_edges"]],
                 ["membership cells actually stored", st["stored_membership_cells"]],
                 ["storage saving",
                  f"{st['implied_graph_edges'] - st['stored_membership_cells']} cells "
                  f"({100 - 100*st['stored_membership_cells']//max(st['implied_graph_edges'],1)}%)"]]), "",
         "## 3. Node census", "",
         _table(["kind", "count"], [[k, v] for k, v in sorted(st["kinds"].items())]), "",
         "## 4. Line address table (all 109)", "",
         _table(["#", "total", "numeral", "dr", "ring", "bucket", "opcode", "address"],
                [[a.n, a.total, a.numeral, a.dr, f"{a.ring}={a.ring_letter}",
                  f"`{a.address.bucket}`", a.opcode, f"`{a.key}`"] for a in J.lines]), "",
         "## 5. Letter address table", "",
         _table(["letter", "name", "L0 value", "L0 address", "L1 value", "L1 address",
                 "ring", "opcode"],
                [[c, NAME[c], VALUE[c], f"`{HashAddress(VALUE[c],0,'0').key}`",
                  depth_series(c, 1)[1],
                  f"`{HashAddress(depth_series(c,1)[1],1,'0').key}`",
                  HashAddress(VALUE[c], 0, "0").ring_letter,
                  HashAddress(VALUE[c], 0, "0").opcode] for c in BY_ORDER]), "",
         "## 6. Executing an address", "",
         "An address is callable. Dispatch is by `value mod 4` onto the bootloader's four "
         "inherited operations (doc 03):", ""]
    demo = []
    for a in J.lines[:6]:
        nid = None
        for n in g.nodes.values():
            if n.kind == "line" and n.meta.get("n") == a.n:
                nid = n.nid
                break
        reached = g.execute(nid)
        demo.append([a.n, f"`{a.key}`", a.opcode,
                     (reached.label[:34] + "…") if reached else "—",
                     reached.kind if reached else "—"])
    L += [_table(["from line", "address", "opcode", "reaches", "kind"], demo), "", ]
    return "\n".join(L)


# ---------------------------------------------------------------- doc 06
def doc_06(J: Jazariyyah) -> str:
    g = J.graph()
    st = g.stats()
    L = ["# ٠٦ — البنية الهجينة: شجرة وشبكة",
         "# 06 — The graph-tree hybrid: local branching and global addressing",
         "", BANNER, "",
         "One node set carries two independent link systems.", "",
         "```",
         "TREE  (local, explicit)          GRAPH (global, containerised)",
         "  corpus                           C<dr>.<ring>",
         "    └── section  ×17                 ├── node  (any kind, any depth)",
         "          └── line  ×109             ├── node",
         "                └── hemistich ×218   └── node",
         "                      └── word ×1005      ⇢ every pair one hop apart",
         "                            └── expansion (grafted on demand)",
         "```", "",
         "## 1. Tree edges", "",
         "Parent/child comes from containment (a line contains hemistichs, a hemistich "
         "contains words) and from expansion (a letter contains the letters of its name). "
         "Siblings are the ordered children of one parent, so recitation order is preserved "
         "exactly.", "",
         _table(["level", "kind", "count", "branching"],
                [["0", "corpus", st["kinds"].get("corpus", 0), "—"],
                 ["1", "section", st["kinds"].get("section", 0),
                  f"{st['kinds'].get('section',0)}"],
                 ["2", "line", st["kinds"].get("line", 0),
                  f"~{st['kinds'].get('line',0)//max(st['kinds'].get('section',1),1)} per section"],
                 ["3", "hemistich", st["kinds"].get("hemistich", 0), "2 per line"],
                 ["4", "word", st["kinds"].get("word", 0),
                  f"~{st['kinds'].get('word',0)//max(st['kinds'].get('hemistich',1),1)} per hemistich"]]), "",
         "## 2. Graph edges — the constellations", "",
         "A node's container handle is `C<digital-root>.<ring position>`, both derived from "
         "its abjad total. Two nodes anywhere in the corpus that agree on both are in the same "
         "container and are one hop apart, whatever their depth or section.", "",
         f"There are **{st['containers']}** containers over **{st['nodes']}** nodes; "
         f"**{st['populated_containers']}** hold more than one member; the largest holds "
         f"**{st['largest_container']}**.", "",
         "### Largest containers", ""]
    big = sorted(g.by_bucket.items(), key=lambda kv: (-len(kv[1]), kv[0]))[:10]
    rows = []
    for handle, members in big:
        sample = [g.nodes[m] for m in members[:6]]
        rows.append([f"`{handle}`", len(members),
                     " · ".join(n.label[:14] for n in sample) + (" …" if len(members) > 6 else "")])
    L += [_table(["container", "members", "sample"], rows), "",
          "## 3. Where the two systems disagree", "",
          "The interesting structure is where a graph edge crosses a tree boundary — two lines "
          "in different chapters that share an address. Those are the context jumps.", ""]
    by = collections.defaultdict(list)
    for a in J.lines:
        by[a.total].append(a)
    cross = [(v, ls) for v, ls in sorted(by.items()) if len(ls) > 1]
    rows = []
    for v, ls in cross:
        rows.append([v, to_abjad_numeral(v),
                     " ⇄ ".join(f"{a.n}" for a in ls),
                     " ⇄ ".join(a.section for a in ls),
                     "same chapter" if len({a.section for a in ls}) == 1 else "**crosses chapters**"])
    L += [_table(["address", "numeral", "lines", "chapters", "relation"], rows), "",
          f"{len(cross)} pairs of lines out of {len(J.lines)} share an exact address. Each is a "
          "direct pointer edge: from either line the other is reachable in one hop without "
          "traversing the tree.", ""]
    for v, ls in cross:
        L += [f"**Address {v}:**", ""]
        for a in ls:
            L += [f"- line {a.n} ({a.section}) — {a.sadr} ✽ {a.ajuz}"]
        L += [""]
    L += ["## 4. Traversal", "",
          "```",
          "tree walk    : parent / children / siblings        -- order-preserving",
          "graph jump   : container(node) -> [equivalents]    -- order-destroying, O(1)",
          "hybrid route : jump, then walk down the new tree   -- context switch",
          "```", "",
          "The four bootloader opcodes are exactly this instruction set: three tree moves "
          "(PARENT, GRANDPARENT, IDENTITY) and one graph move (SHIFT). See doc 03.", ""]
    return "\n".join(L)


# ---------------------------------------------------------------- doc 07
def doc_07(J: Jazariyyah) -> str:
    L = ["# ٠٧ — تاء التأنيث: بتّ الحالة والتوجيه",
         "# 07 — Tāʾ marbūṭah vs. tāʾ maftūḥah as routing state", "", BANNER, "",
         "## 1. The rule the poem states", "",
         "Line 8 makes the orthography of the feminine ending an explicit subject of study:", "",
         f"> {J.line(8).sadr}  ✽  {J.line(8).ajuz}", "",
         "and the poem devotes a whole chapter (باب التاءات, lines "
         f"{[a.n for a in J.lines if a.section=='التاءات'][0]}–"
         f"{[a.n for a in J.lines if a.section=='التاءات'][-1]}) to the words in which the "
         "feminine ending is written **open** (ت) in the Uthmanic rasm where ordinary "
         "spelling would close it (ة).", "",
         "## 2. Why this is a bit and not a spelling quirk", "",
         "The ending is genuinely bistable in performance: stopping on it realises it as "
         "hāʾ, continuing realises it as tāʾ. Two readings, one grapheme:", "",
         "```", "waqf  (pausal)      ة → ه =   5     state bit S0",
         "waṣl  (continuous)  ة → ت = 400     state bit S1",
         "                    ----------------",
         "                    stride  = 395", "```", "",
         f"**Every** state-bearing word therefore has two addresses exactly **{STRIDE}** apart. "
         "A word carrying *k* such graphemes is a *k*-bit register.", "",
         "## 3. The باب التاءات register", "",
         "The chapter's word list, each in both realisations:", ""]
    pairs = open_ta_pairs()
    L += [_table(["closed (ة)", "value", "open (ت)", "value", "Δ"],
                 [[p["closed"], p["closed_value"], p["open"], p["open_value"], p["delta"]]
                  for p in pairs]), "",
          f"All {len(pairs)} rows show Δ = **{STRIDE}** without exception. The chapter is a "
          f"fixed-stride bit-field: {len(pairs)} independent bits, uniform spacing.", "",
          "Two of its entries collide exactly:", ""]
    coll = collections.defaultdict(list)
    for p in pairs:
        coll[p["closed_value"]].append(p["closed"])
    for v, ws in sorted(coll.items()):
        if len(ws) > 1:
            L += [f"- **{' = '.join(ws)} = {v}** — indistinguishable by address; only the tree "
                  "position separates them."]
    L += ["", "## 4. State across the whole poem", ""]
    bearing = [a for a in J.lines if a.ta_bits]
    total_bits = sum(a.ta_bits for a in J.lines)
    L += [_table(["quantity", "value"],
                 [["lines carrying ≥1 state bit", len(bearing)],
                  ["lines with fixed state", len(J.lines) - len(bearing)],
                  ["total bits in the corpus", total_bits],
                  ["widest line", f"line {max(J.lines, key=lambda a: a.ta_bits).n} "
                                  f"({max(a.ta_bits for a in J.lines)} bits)"],
                  ["addressable states of the corpus", f"2^{total_bits}"]]), "",
          "### Every state-bearing line", "",
          _table(["#", "bits", "state words", "waqf total", "waṣl total", "Δ", "section"],
                 [[a.n, a.ta_bits, " · ".join(a.ta_words), a.total, a.total_wasl,
                   a.ta_delta, a.section] for a in bearing]), "",
          "Δ is always a multiple of 395, and the multiple *is* the bit count — which is the "
          "check that the state model is sound.", "",
          "## 5. Routing on the bit", "",
          "Because the state bit is the S component of the hash address, the same word "
          "occupies two different containers depending on how it is recited. Collisions "
          "across the state boundary are real edges:", ""]
    wi = _word_index(J)
    byval = collections.defaultdict(list)
    for w in wi:
        byval[w["value"]].append(w["surface"])
    rows = []
    for a in bearing[:40]:
        for w in a.ta_words:
            sw = analyse_word(w)
            hit = byval.get(sw.wasl, [])
            if hit:
                rows.append([w, sw.waqf, sw.wasl, " · ".join(hit[:4]),
                             f"line {a.n}"])
    if rows:
        L += ["A word's *waṣl* address landing on another word's *waqf* address:", "",
              _table(["state word", "waqf addr", "waṣl addr", "occupied at waṣl addr by",
                      "from"], rows[:20]), ""]
    else:
        L += ["No cross-state collisions occur in this corpus.", ""]
    return "\n".join(L)


# ---------------------------------------------------------------- doc 08
DEMO_TOKENS = ["برشق", "زحقل", "غضنف", "طمشر", "قزطح", "ضظغ", "هوزح", "سنقر"]


def doc_08(J: Jazariyyah) -> str:
    L = ["# ٠٨ — توليد الجذور خارج المعجم",
         "# 08 — Non-dictionary root synthesis", "", BANNER, "",
         "## 1. What this does", "",
         "A string with no lexical entry is still fully determined structurally. Its letters "
         "have weights; the weights give an address; the address has neighbours inside the "
         "corpus; and the poem itself states where each of its letters is articulated. A "
         "reading can be assembled from those four facts alone.", "",
         "**What it is not.** This is a formal placement of a token inside this corpus. It is "
         "not a claim about attested Arabic lexicography, and a definition produced here is "
         "not evidence that a word exists or means anything in the language. The procedure is "
         "deterministic, which makes it checkable — not authoritative.", "",
         "## 2. The two projections", "",
         "Every token is read twice, at two expansion depths:", "",
         _table(["projection", "depth", "what it reads"],
                [["إنسيّ / manifest", 0, "the surface rasm as written — letters at face weight"],
                 ["جنّيّ / hidden", 1, "each letter replaced by its spelled name, then summed"]]), "",
         "These are not two systems but one computation at two depths. The manifest reading is "
         "what the eye counts; the hidden reading is what the name of each sign counts.", "",
         "## 3. Procedure", "",
         "```",
         "1. normalise      strip diacritics; fold hamza carriers onto ا; resolve ة by state",
         "2. deconstruct    letter -> integer, by table look-up",
         "3. root           drop ال, prefer strong consonants, re-admit weak ones if short",
         "4. project        J at depth 0 (manifest) and depth 1 (hidden)",
         "5. address        J -> digital root, ring position, container handle",
         "6. cluster        corpus words nearest by |Δ|; dominant chapter of the container",
         "7. render         compose the reading from steps 3–6",
         "```", "",
         "## 4. Worked syntheses", ""]
    for tok in DEMO_TOKENS:
        s = synthesise(J, tok)
        L += [f"### {tok}", "",
              "**Deconstruction.** " + " + ".join(f"{c}={v}" for c, v in s.working)
              + f" = **{s.manifest.value}**", "",
              _table(["projection", "value", "numeral", "dr", "ring", "address"],
                     [[s.manifest.name, s.manifest.value, s.manifest.numeral, s.manifest.dr,
                       f"{s.manifest.ring}={s.manifest.ring_letter}", f"`{s.manifest.key}`"],
                      [s.hidden.name, s.hidden.value, s.hidden.numeral, s.hidden.dr,
                       f"{s.hidden.ring}={s.hidden.ring_letter}", f"`{s.hidden.key}`"]]), "",
              f"**Root.** ({' · '.join(s.root)}) = {s.root_value}   |   "
              f"**in the poem's lexicon:** {'yes' if s.in_lexicon else 'no'}", "",
              "**Articulation, as the poem states it:**", "",
              _table(["letter", "makhraj", "attributes", "poem line"],
                     [[a["letter"], a["makhraj"],
                       "، ".join(s.attributes[a["letter"]]) or "—",
                       a["cited_line"] or "—"] for a in s.articulation]), "",
              "**Nearest corpus words (manifest):**", "",
              _table(["word", "value", "Δ", "line(s)", "chapter"],
                     [[n["word"], n["value"], n["distance"],
                       ", ".join(str(x) for x in n["lines"]), n["section"]]
                      for n in s.manifest.neighbours]), "",
              "**Rendered reading:**", "", "> " + s.definition, "", "---", ""]
    L += ["## 5. Determinism check", "",
          "Re-running the procedure on the same token yields the same address, the same "
          "neighbours and the same text, because every step is a table look-up or a sum. "
          "Two tokens with the same letters in any order share a manifest address — the "
          "manifest projection is order-blind, the root extraction is not:", ""]
    rows = []
    for t in ["زحقل", "قلزح", "حلزق"]:
        s = synthesise(J, t)
        rows.append([t, s.manifest.value, "".join(s.root), s.hidden.value])
    L += [_table(["token", "manifest", "root", "hidden"], rows), "",
          "Same manifest value, different roots — which is precisely the information the tree "
          "carries that the scalar address does not.", ""]
    return "\n".join(L)


# ---------------------------------------------------------------- doc 09
def doc_09(J: Jazariyyah) -> str:
    g = J.graph()
    L = ["# ٠٩ — خريطة التكافؤ بالباقي: الكواكب والبروج",
         "# 09 — Constellation map: modulo equivalence across the corpus", "", BANNER, "",
         "## 1. The two coordinates", "",
         "```",
         "digital root   dr(J) = 1 + (J-1) mod 9        9 classes   -- the 'declination'",
         "ring position  r(J)  = 1 + (J-1) mod 28       28 classes  -- the 'right ascension'",
         "container      C<dr>.<r>                      up to 252 cells",
         "```", "",
         "Both are hand-computable: dr by casting out nines, r by casting out twenty-eights. "
         "Two nodes agreeing on both are one hop apart regardless of where they sit in the "
         "tree.", "",
         "## 2. Digital-root classes over the 109 lines", ""]
    h = collections.Counter(a.dr for a in J.lines)
    L += [_table(["dr", "letter", "lines", "histogram"],
                 [[d, letter_for_value(d), h[d], "█" * h[d]] for d in range(1, 10)]), "",
          f"Expected under a uniform model: {len(J.lines)/9:.1f} per class. Observed range "
          f"{min(h.values())}–{max(h.values())}. The distribution is close to flat, which is "
          "what makes the digital root usable as a hash component rather than as a signal.", "",
          "## 3. Ring classes (mod 28)", ""]
    hr = collections.Counter(a.ring for a in J.lines)
    L += [_table(["ring", "letter", "name", "lines"],
                 [[i, BY_ORDER[i-1], NAME[BY_ORDER[i-1]], hr.get(i, 0)]
                  for i in range(1, 29)]), "",
          f"Occupied ring positions: **{len(hr)}/28**. "
          f"Empty: {', '.join(f'{i}={BY_ORDER[i-1]}' for i in range(1,29) if i not in hr) or 'none'}.",
          "", "## 4. The populated containers", ""]
    linebuckets = collections.defaultdict(list)
    for a in J.lines:
        linebuckets[a.address.bucket].append(a.n)
    multi = {k: v for k, v in linebuckets.items() if len(v) > 1}
    L += [f"Of {len(linebuckets)} containers occupied by lines, **{len(multi)}** hold more "
          "than one line. Those are the corpus's context jumps:", "",
          _table(["container", "lines", "chapters"],
                 [[f"`{k}`", ", ".join(str(x) for x in v),
                   " ⇄ ".join(sorted({J.line(x).section for x in v}))]
                  for k, v in sorted(multi.items(), key=lambda kv: (-len(kv[1]), kv[0]))]), "",
          "## 5. The alphabet as its own constellation", "",
          "Applying the same two coordinates to the 28 letters:", "",
          _table(["letter", "value", "dr", "ring", "container", "opcode"],
                 [[c, VALUE[c], digital_root(VALUE[c]),
                   HashAddress(VALUE[c], 0, "0").ring,
                   f"`{HashAddress(VALUE[c],0,'0').bucket}`",
                   HashAddress(VALUE[c], 0, "0").opcode] for c in BY_ORDER]), "",
          f"Sum of the whole alphabet = **{ALPHABET_SUM}**, digital root "
          f"**{digital_root(ALPHABET_SUM)}**, numeral {to_abjad_numeral(ALPHABET_SUM)}.", "",
          "## 6. Word-level constellations", ""]
    wi = _word_index(J)
    byval = collections.defaultdict(list)
    for w in wi:
        byval[w["value"]].append(w)
    dense = sorted(((v, ws) for v, ws in byval.items() if len(ws) >= 5),
                   key=lambda kv: (-len(kv[1]), kv[0]))
    L += [f"{len(wi)} distinct words occupy {len(byval)} distinct addresses. The densest:", "",
          _table(["address", "numeral", "count", "words"],
                 [[v, to_abjad_numeral(v), len(ws), " · ".join(w["surface"] for w in ws)]
                  for v, ws in dense[:15]]), "",
          "Each row is a clique: any of those words reaches any other in one hop. This is the "
          "instantaneous context-jumping the architecture is for — from `قطب` in the chapter "
          "on letter attributes to `وصحبه` in the opening doxology, because both weigh 111.", ""]
    return "\n".join(L)


# ---------------------------------------------------------------- doc 10
def doc_10(J: Jazariyyah) -> str:
    g = J.graph()
    st = g.stats()
    t = J.totals()
    wi = _word_index(J)
    L = ["# ١٠ — حصاد المتن: نتائج وتحقّق",
         "# 10 — Corpus-wide findings and verification record", "", BANNER, "",
         "## 1. Provenance", "",
         _table(["field", "value"],
                [["work", J.meta["work"]], ["author", J.meta["author"]],
                 ["died", f"{J.meta['author_died_ah']} AH"],
                 ["composed", f"{J.meta['composed_ah']} AH"],
                 ["metre", J.meta["metre"]],
                 ["primary witness", J.meta["provenance"]["primary"]],
                 ["collated against", J.meta["provenance"]["collated_against"]],
                 ["variant hemistichs between witnesses",
                  J.meta["recension_apparatus"]["variant_hemistichs"]]]), "",
         "**Caveat carried through every document in this repository:** the text is a "
         "transmitted recension, not a critical edition. Two witnesses were collated and they "
         f"disagree in {J.meta['recension_apparatus']['variant_hemistichs']} hemistichs. "
         "Collate against a printed critical edition before citing any of this in scholarship. "
         "The engine is exact; the corpus it runs on is only as good as its witnesses.", "",
         "### Corrections applied", "",
         _table(["line", "half", "from", "to", "why"],
                [[c["line"], c["half"], c["from"], c["to"],
                  "second witness and the rhyme both show a dropped final letter"]
                 for c in J.meta.get("corrections", {}).get("applied", [])]), "",
         "## 2. Scalar summary", "",
         _table(["quantity", "value", "numeral", "dr"],
                [["sum of all 109 lines", t["sum"], "—", digital_root(t["sum"])],
                 ["sum of lines 1–107", sum(a.total for a in J.lines[:107]), "—",
                  digital_root(sum(a.total for a in J.lines[:107]))],
                 ["sum of lines 108–109", sum(a.total for a in J.lines[107:]), "—",
                  digital_root(sum(a.total for a in J.lines[107:]))],
                 ["lightest line (#%d)" % t["argmin"], t["min"], to_abjad_numeral(t["min"]),
                  digital_root(t["min"])],
                 ["heaviest line (#%d)" % t["argmax"], t["max"], to_abjad_numeral(t["max"]),
                  digital_root(t["max"])],
                 ["heaviest − lightest", t["max"] - t["min"], "—",
                  digital_root(t["max"] - t["min"])],
                 ["mean line", t["mean"], "—", digital_root(t["mean"])],
                 ["distinct words", len(wi), "—", "—"],
                 ["nodes in the graph-tree", st["nodes"], "—", "—"]]), "",
         "## 3. Findings", "", "### F1 — الْعَدَدْ weighs 109", "",
         "The colophon states the count as قاف وزاي = 107. Its own final word, الْعَدَدْ, "
         f"weighs {abjad('العدد')}: ا(1)+ل(30)+ع(70)+د(4)+د(4). The number stated and the "
         "number transmitted are both present in one hemistich. Only two words in the entire "
         "poem weigh 109 — الْعَدَدْ and قَطٍ, the latter being the abjad spelling of 109. "
         "(Arithmetic only; authorial intent is not claimed.)", "",
         "### F2 — the paradox is positional, not arithmetical", "",
         "The two collated witnesses carry the same closing lines in different order. Where "
         "the colophon stands last it reads as a false statement about a 109-line poem; where "
         "it stands at ordinal 107 it is true of its own position and the doxology follows as "
         "an appendix. The contradiction is manufactured by the splice point. See doc 02 §5.", "",
         "### F3 — the feminine ending is a uniform-stride bit field", "",
         f"All {len(open_ta_pairs())} words of باب التاءات show Δ = {STRIDE} between their "
         "closed and open realisations, without exception, because the difference is always "
         f"ت(400) − ه(5). The corpus carries {sum(a.ta_bits for a in J.lines)} such bits over "
         f"{len([a for a in J.lines if a.ta_bits])} lines. Uniform stride is what makes the "
         "state bit safe to put in the address.", "",
         "### F4 — three pairs of lines share an exact address", ""]
    by = collections.defaultdict(list)
    for a in J.lines:
        by[a.total].append(a)
    cross = [(v, ls) for v, ls in sorted(by.items()) if len(ls) > 1]
    L += [_table(["address", "lines", "chapters"],
                 [[v, " ⇄ ".join(str(a.n) for a in ls),
                   " ⇄ ".join(a.section for a in ls)] for v, ls in cross]), "",
          "All three cross chapter boundaries, so each is a genuine graph edge rather than an "
          "artefact of local similarity.", "",
          "### F5 — the heaviest line is the ظاء inventory", "",
          f"Line {t['argmax']} weighs {t['max']}, more than {t['max']//t['min']}× the lightest. "
          "It is the line enumerating words containing ظ (weight 900), so the weight is "
          "carried by the subject matter itself — the poem's heaviest line is heavy *because* "
          "it is about the heaviest letter.", "",
          f"> {J.line(t['argmax']).sadr}  ✽  {J.line(t['argmax']).ajuz}", "",
          f"The lightest, line {t['argmin']}, is the doxology — short words, light letters:", "",
          f"> {J.line(t['argmin']).sadr}  ✽  {J.line(t['argmin']).ajuz}", "",
          f"Their difference is exactly **{t['max']-t['min']}**.", "",
          "### F6 — the densest word-addresses", ""]
    byval = collections.defaultdict(list)
    for w in wi:
        byval[w["value"]].append(w["surface"])
    dense = sorted(((v, ws) for v, ws in byval.items() if len(ws) >= 6),
                   key=lambda kv: (-len(kv[1]), kv[0]))
    L += [_table(["address", "count", "words"],
                 [[v, len(ws), " · ".join(ws)] for v, ws in dense]), "",
          f"Address 111 — the depth-1 expansion of ا — is occupied by "
          f"{len(byval.get(111,[]))} words of the poem. The origin letter's own name-value is "
          "one of the corpus's busiest addresses.", "",
          "### F7 — all four opcodes are exercised", ""]
    h = collections.Counter(a.opcode for a in J.lines)
    L += [_table(["opcode", "lines"], [[o, h[o]] for o in OPS_ORDER]), "",
          "No line of the poem is unreachable and no operation is dead code.", "",
          "## 4. Verification record", "",
          "Every table in these ten documents is regenerated from `data/jazariyyah.json` and "
          "`data/letters.json` by `python3 -m abjad.cli report`. Nothing is transcribed by "
          "hand. The Python and TypeScript engines are cross-checked against each other on "
          "the corpus; see `make verify`.", "",
          _table(["check", "result"],
                 [["line count", f"{len(J.lines)} == {J.meta['line_count']}"],
                  ["colophon ordinal == authorial count",
                   f"{J.meta['authorial_count_line']} == {J.meta['authorial_count']}"],
                  ["ا at depth 1", f"{depth_series('ا',1)[1]} == 111"],
                  ["ق + ز", f"{VALUE['ق']+VALUE['ز']} == 107"],
                  ["ق + ط", f"{VALUE['ق']+VALUE['ط']} == 109"],
                  ["الْعَدَدْ", f"{abjad('العدد')} == 109"],
                  ["ta stride", f"{STRIDE} == 395"],
                  ["bootloader sums", f"{[s for _,_,s,_,_ in BOOTLOADER]} == [3, 7, 11, 15]"],
                  ["alphabet sum", f"{ALPHABET_SUM}"]]), ""]
    return "\n".join(L)


DOCS = [
    ("01_jazariyyah_109_interleaved_recitation.md", doc_01),
    ("02_qaf_zay_cipher_resolution.md", doc_02),
    ("03_primordial_alphabet_bootloader.md", doc_03),
    ("04_nested_expansion_atlas.md", doc_04),
    ("05_hash_address_lookup_tables.md", doc_05),
    ("06_graph_tree_hybrid_topology.md", doc_06),
    ("07_ta_marbutah_routing_states.md", doc_07),
    ("08_non_dictionary_root_synthesis.md", doc_08),
    ("09_constellation_modulo_map.md", doc_09),
    ("10_corpus_findings_and_verification.md", doc_10),
]


def generate(outdir: str = "docs", J: Jazariyyah = None) -> List[str]:
    J = J or Jazariyyah()
    os.makedirs(outdir, exist_ok=True)
    written = []
    for name, fn in DOCS:
        path = os.path.join(outdir, name)
        with open(path, "w", encoding="utf-8") as f:
            f.write(fn(J).rstrip() + "\n")
        written.append(path)
    return written
